---
- name: Example Playbook
  hosts: hosts  # The group or list of hosts to target
  become: yes  # Optional, if you need privilege escalation (sudo)
            
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started

